apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment
  template:
    metadata:
      labels:
        app: assessment
    spec:
      containers:
      - name: assessment
        image: gonzalomarcote/assessment:latest
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: assessment-service
spec:
  selector:
    app: assessment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
